### ISSUE TITLE
Obsolete Header with two bins

### ISSUE THREAD

**Issue by velusgautam** [mdn/kumascript#1275] opened 2019-11-04 10:02 UTC
There are two bins showing in obsolete header

![Screenshot 2019-11-04 at 10 58 34](https://user-images.githubusercontent.com/8556085/68112778-6fa2ed00-fef2-11e9-8c86-35143c6813cb.png)

**Comment by velusgautam** [comment] 2019-11-04 10:11
Created a PR to fix this.
https://github.com/mdn/kumascript/pull/1276

**Comment by ExE-Boss** [comment] 2019-11-04 16:28
Duplicate of mdn/kuma#6035

**Closed** 2019-11-10 22:20 UTC
