### ISSUE TITLE
{{csssyntax}} doesn't alert when data missing from json file.

### ISSUE THREAD

**Issue by jpmedley** [mdn/kumascript#669] opened 2018-04-06 18:46 UTC
I've found a csssyntax macro error on multiple pages with no apparent reason. I suspect the macro itself and not how its used.  Here are some examples.

* https://developer.mozilla.org/en-US/docs/Web/CSS/:host()
* https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context()

**Comment by jwhitlock** [comment] 2018-04-09 13:35
The issue is that ``:host()`` and ``:host-context()`` are not in [mdn/data/css/selectors.json](https://github.com/mdn/data/blob/master/css/selectors.json), and the [csssyntax](https://github.com/mdn/kumascript/blob/master/macros/csssyntax.ejs#L446) macro fails with an exception if the selector doesn't exist. Attempts to fix are in #671 and #684.

**Comment by jpmedley** [comment] 2018-04-09 14:03
Is it possible to make it provide a meaningful message?

**Comment by jwhitlock** [comment] 2018-04-09 14:24
Here's the error message that you can see if you are logged in:

<img width="723" alt="screenshot 2018-04-09 09 19 44" src="https://user-images.githubusercontent.com/286017/38503292-4a053434-3bd7-11e8-9499-2c32950bfff4.png">

The message could be improved by raising an exception with the message 'host:() not found in selectors.json', instead of attempting to access ``.syntax`` of an undefined variable.

**Comment by jpmedley** [comment] 2018-04-09 15:12
That's exactly what I had in mind.

**Comment by jwhitlock** [comment] 2018-04-26 18:39
With PR #687 merged and deployed, this has changed from a KumaScript error to an in-content error message:

![syntax-not-found](https://user-images.githubusercontent.com/286017/39325205-37ceef34-4957-11e8-90e1-071638efb274.png)

**Closed by jwhitlock** 2018-04-26 18:39 UTC
